apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: examxv2-frontend-pdb
  labels:
    app: examxv2-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: examxv2-frontend

