apiVersion: apps/v1
kind: Deployment
metadata:
  name: examx-print-service
  labels:
    app: examx-print-service
  annotations:
    change-cause: "Initial deployment of print service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examx-print-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: examx-print-service
    spec:
      containers:
        - name: examx-print-service
          image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examx-print-service:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
