apiVersion: apps/v1
kind: Deployment
metadata:
  name: examxv2-frontend
  labels:
    app: examxv2-frontend
  annotations:
    change-cause: "Added change-cause annotation to deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examxv2-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: examxv2-frontend
    spec:
      volumes:
        - name: nginx-configuration
          configMap:
            name: frontend-nginx-config
      containers:
        - name: examxv2-frontend
          image: "399600302704.dkr.ecr.ap-south-1.amazonaws.com/examxv2-evolution:Updated_Docker_file___Expose_p-20241010-095912-d771fcd"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          ports:
            - containerPort: 80
          volumeMounts:  
            - name: nginx-configuration
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 10
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # startupProbe:
          #   httpGet:
          #     path: /health
          #     port: 80
          #   failureThreshold: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5